import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "@/store/Provider";
import { ReactQuery } from "@/store/ReactQuery";
import PrivateRoute from "@/store/PrivateRoute";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next 13",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQuery>
          <Providers>
            <Navbar />
            <PrivateRoute>{children}</PrivateRoute>
          </Providers>
        </ReactQuery>
      </body>
    </html>
  );
}
